[general]
name = "sonic-moe"
license = "Apache-2.0"
backends = ["cuda"]
version = 1

[general.hub]
repo-id = "kernels-community/sonic-moe"

[general.cuda]
minver = "12.9"
python-depends = [
    "nvidia-cutlass-dsl==4.4.2",
    "apache-tvm-ffi>=0.1.6,<0.2",
    "torch-c-dlpack-ext",
]
